AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for BIS-Cloud
Globals:
    Function:
        Timeout: 900

Parameters:
    PackagesLayerArn:
        Type: String
        Default: arn:aws:lambda:us-east-1:320132171574:layer:PythonPackagesLayer:6

Resources:
    CustomAppLayers:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: CustomAppLayers
            Description: Owner modules
            ContentUri: ../../CloudCore/python
            RetentionPolicy: Retain
            LicenseInfo: MIT
            CompatibleRuntimes:
                - python3.6
        Metadata:
            BuildMethod: python3.6

    UsersDynamoStreamHandle:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 2048
            Timeout: 20
            FunctionName: UsersDynamoStreamHandle
            Description: Handles dynamodb streams from users table
            CodeUri: serverless/dynamoStream/
            Handler: dynamoStreamHandler.lambda_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                # Give DynamoDB Full Access to your Lambda Function
                - AmazonDynamoDBFullAccess
                - AmazonSNSFullAccess
                - AWSLambdaDynamoDBExecutionRole
            Events:
                Stream:
                    Type: DynamoDB
                    Properties:
                        Stream: arn:aws:dynamodb:us-east-1:320132171574:table/Users/stream/2021-01-12T16:46:15.772
                        BatchSize: 100
                        StartingPosition: TRIM_HORIZON

    StartSearchEngineInstance:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: StartSearchEngineInstance
            Description: Handles the start of a search engine Ec2 instance
            CodeUri: serverless/serverManager/
            Handler: managerHandler.start_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
                - IAMFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-START-SERVICE

    TerminateSearchEngineInstance:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: TerminateSearchEngineInstance
            Description: Handles the termination of a search engine Ec2 instance
            CodeUri: serverless/serverManager/
            Handler: managerHandler.terminate_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-STOP-SERVICE


    ModifyStateSearchEngineInstance:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 5
            FunctionName: ModifyStateSearchEngineInstance
            Description: Handles the state swap of a search engine Ec2 instance
            CodeUri: serverless/serverManager/
            Handler: managerHandler.modify_state_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-PAUSE-SERVICE

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Users
            StreamSpecification:
                StreamViewType: NEW_IMAGE
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: N
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
