AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for BIS-Cloud

Globals:
    Function:
        Runtime: python3.6
        Layers:
            - arn:aws:lambda:us-east-1:436783151981:layer:PythonPackagesLayer:3 # Change account ID also here

Parameters:
    AccountId:
        Type: String
        Default: 436783151981

Resources:
    IterStateMachineLogs:
        Type: AWS::Logs::LogGroup

    # state machine  ----------------------------------------------------------------------------------------
    IteratorStateMachine:
        Type: AWS::Serverless::StateMachine
        Properties:
            Type: EXPRESS
            Name: IteratorStateMachine
            DefinitionUri: statemachine/loop_state_machine.asl.json
            DefinitionSubstitutions:
                FlexSmIteratorFunctionArn: !GetAtt FlexSmIterator.Arn
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0/1 * * * ? *)
            Logging:
                Destinations:
                    -   CloudWatchLogsLogGroup:
                            LogGroupArn: !GetAtt IterStateMachineLogs.Arn
                IncludeExecutionData: true
                Level: ALL
            Policies:
                -   LambdaInvokePolicy:
                        FunctionName: !Ref FlexSmIterator
                - CloudWatchLogsFullAccess

    # dynamo db  ----------------------------------------------------------------------------------------
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Users
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: S
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

    BlocksTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Blocks
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: S
                -   AttributeName: block_id
                    AttributeType: N
                -   AttributeName: station_id
                    AttributeType: S
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
                -   AttributeName: block_id
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            GlobalSecondaryIndexes:
                -   IndexName: Blocks_GSI1
                    KeySchema:
                        -   AttributeName: station_id
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 5
                        WriteCapacityUnits: 5

    OffersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Offers
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: S
                -   AttributeName: offer_id
                    AttributeType: S
                -   AttributeName: station_id
                    AttributeType: S
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
                -   AttributeName: offer_id
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

            GlobalSecondaryIndexes:
                -   IndexName: Offers_GSI1
                    KeySchema:
                        -   AttributeName: station_id
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 5
                        WriteCapacityUnits: 5

    # Lambda layers ----------------------------------------------------------------------------------------
    CustomAppLayers:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: CustomAppLayers
            Description: Owner modules
            ContentUri: ../../CloudCore/python
            RetentionPolicy: Retain
            LicenseInfo: MIT
            CompatibleRuntimes:
                - python3.6
        Metadata:
            BuildMethod: python3.6

    # Lambdas section ---------------------------------------------------------------------------------------
    FlexSmIterator:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 512
            Timeout: 20
            FunctionName: FlexSmIterator
            Description: allow to iterate every second base on the state machine trigger
            CodeUri: serverless/searchEngine/
            Handler: flexSmIterator.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AWSLambdaFullAccess
                - AWSStepFunctionsFullAccess

    SleepSearchEngine:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: SleepSearchEngine
            Description: Handles the put to sleep of a search engine Ec2 instance for 30 minutes
            CodeUri: serverless/searchEngine/
            Handler: sleepSearch.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
                - AmazonDynamoDBFullAccess
                - AWSLambdaDynamoDBExecutionRole
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-SLEEP-TOPIC'

    SearchEngineCloudLogs:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 256
            Timeout: 5
            FunctionName: SearchEngineCloudLogs
            Description:
            CodeUri: serverless/logging/
            Handler: engineLogger.lambda_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
                - CloudWatchLogsFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-LOGS-TOPIC'

    FlexListActiveUsers:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 10240
            Timeout: 301
            FunctionName: FlexListActiveUsers
            Description: Check dynamo db and get the latest active users (after 30 mins sleep) search=True
            CodeUri: serverless/searchEngine/
            Handler: flexListActiveUsers.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonSNSFullAccess

    CleanUpTables:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 10240
            Timeout: 361
            FunctionName: CleanUpTables
            Description: every mid night deletes entries older than 48 hours ago in blocks and offers tables
            CodeUri: serverless/cronoLambdas/
            Handler: CleanUpTables.lambda_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(59 23 * * ? *)

    LogAllUsers:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 10240
            Timeout: 900
            FunctionName: LogAllUsers
            Description: every minute log all active users stats to cloudwatch
            CodeUri: serverless/logging/
            Handler: logUserStats.lambda_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - CloudWatchLogsFullAccess
                - AmazonSNSFullAccess
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0/1 * * * ? *)

    UpdateBlocksTable:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: UpdateBlocksTable
            Description: Handles the update of blocks table with the blocks info
            CodeUri: serverless/searchEngine/
            Handler: updateBlocksTable.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
                - AmazonDynamoDBFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-ACCEPTED-TOPIC'

    UpdateOffersTable:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 512
            Timeout: 20
            FunctionName: UpdateOffersTable
            Description: Handles the update of offers table with the offer info
            CodeUri: serverless/searchEngine/
            Handler: updateOffersTable.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
                - AmazonDynamoDBFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-OFFERS-TOPIC'

    NotifyBlockToWeb:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: NotifyBlockToWeb
            Description: Send a post request to a web endpoint with the block info
            CodeUri: serverless/apiGateway/
            Handler: notifyBlockToWeb.lambda_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
                - AmazonDynamoDBFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-ACCEPTED-TOPIC'

    NotifyErrorToWeb:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 512
            Timeout: 20
            FunctionName: NotifyErrorToWeb
            Description: Send a post request to a web endpoint with the error user info
            CodeUri: serverless/apiGateway/
            Handler: notifyErrorToWeb.lambda_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonSNSFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: !Sub 'arn:aws:sns:us-east-1:${AccountId}:SE-ERROR-TOPIC'

    # api gateway lambdas ----------------------------------------------------------------------------------------
    ApiCreateUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiCreateUser
            Description: Handles creation of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: createUser.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess
            Events:
                Endpoints:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: post

    ApiDeleteUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiDeleteUser
            Description: Handles deletion of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: deleteUser.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess
            Events:
                Endpoints:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: delete

    ApiUpdateUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiUpdateUser
            Description: Handles update of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: updateUser.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess
            Events:
                Endpoints:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: put

    ApiReadUserBlocks:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiReadUserBlocks
            Description: Handles the reading of the user's blocks on the Blocks table
            CodeUri: serverless/apiGateway/
            Handler: readUserBlocks.function_handler
            Layers:
                - !Ref CustomAppLayers
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess
            Events:
                Endpoints:
                    Type: Api
                    Properties:
                        Path: /blocks
                        Method: post