AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for BIS-Cloud
Globals:
    Function:
        Timeout: 900

Parameters:
    PackagesLayerArn:
        Type: String
        Default: arn:aws:lambda:us-east-1:320132171574:layer:PythonPackagesLayer:6

Resources:
    # dynamo db table USERS creation
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Users
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: S
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

    BlocksTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Blocks
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -   AttributeName: user_id
                    AttributeType: S
                -   AttributeName: block_id
                    AttributeType: N
            KeySchema:
                -   AttributeName: user_id
                    KeyType: HASH
                -   AttributeName: block_id
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

    # Lambda layers
    CustomAppLayers:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: CustomAppLayers
            Description: Owner modules
            ContentUri: ../../CloudCore/python
            RetentionPolicy: Retain
            LicenseInfo: MIT
            CompatibleRuntimes:
                - python3.6
        Metadata:
            BuildMethod: python3.6

    # Lambdas section ---------------------------------------------------------------------------------------
    UsersDynamoStreamHandle:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 2048
            Timeout: 20
            FunctionName: UsersDynamoStreamHandle
            Description: Handles dynamodb streams from users table
            CodeUri: serverless/dynamoStream/
            Handler: dynamoStreamHandler.lambda_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                # Give DynamoDB Full Access to your Lambda Function
                - AmazonDynamoDBFullAccess
                - AmazonSNSFullAccess
                - AWSLambdaDynamoDBExecutionRole
            Events:
                Stream:
                    Type: DynamoDB
                    Properties:
                        Stream: !GetAtt DynamoDBTable.StreamArn
                        BatchSize: 100
                        StartingPosition: TRIM_HORIZON

    StartSearchEngineInstance:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: StartSearchEngineInstance
            Description: Handles the start of a search engine Ec2 instance
            CodeUri: serverless/serverManager/
            Handler: managerHandler.start_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
                - IAMFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-START-SERVICE

    TerminateSearchEngineInstance:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: TerminateSearchEngineInstance
            Description: Handles the termination of a search engine Ec2 instance
            CodeUri: serverless/serverManager/
            Handler: managerHandler.terminate_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-STOP-SERVICE

    CronoLambda1Minute:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 2048
            Timeout: 60
            FunctionName: CronoLambda1Minute
            Description: Check dynamo db every minute to wake up every asleep ec2 instance
            CodeUri: serverless/cronoLambdas/
            Handler: sleepStatusCheck.sleep_status_check_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonSNSFullAccess
                - AmazonEC2FullAccess
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0/1 * * * ? *)


    CleanBlocksTable:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 2048
            Timeout: 360
            FunctionName: CleanBlocksTable
            Description: Check dynamo db every day at mid night to delete blocks captured 48 hours ago
            CodeUri: serverless/cronoLambdas/
            Handler: cleanBlocksTable.lambda_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(59 23 * * ? *)


    UpdateBlocksTable:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: UpdateBlocksTable
            Description: Handles the update of blocks table with the blocks info
            CodeUri: serverless/capturedBlocks/
            Handler: updateBlocksTable.function_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonSNSFullAccess
                - AmazonDynamoDBFullAccess
            Events:
                SNSEvent:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-east-1:320132171574:SE-ACCEPTED-BLOCK-SERVICE


    ApiCreateUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiCreateUser
            Description: Handles creation of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: createUser.function_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess


    ApiDeleteUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiDeleteUser
            Description: Handles deletion of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: deleteUsers.function_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess


    ApiUpdateUser:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiUpdateUser
            Description: Handles update of a user in dynamo db Users table
            CodeUri: serverless/apiGateway/
            Handler: updateUser.function_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess


    ApiReadUserBlocks:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 1024
            Timeout: 20
            FunctionName: ApiReadUserBlocks
            Description: Handles the reading of the user's blocks on the Blocks table
            CodeUri: serverless/apiGateway/
            Handler: readUserBlocks.function_handler
            Runtime: python3.6
            Layers:
                - !Ref CustomAppLayers
                - !Ref PackagesLayerArn
            Policies:
                - AmazonDynamoDBFullAccess
                - AmazonAPIGatewayInvokeFullAccess